name: Bug Report
description: File a bug report to help us improve
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 🐛
        
        Before submitting, please check if:
        - [ ] You've searched for existing issues
        - [ ] You've tested on the latest version
        - [ ] All quality checks pass in your environment

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of the N-Queens Game are you using?
      placeholder: e.g., v1.0.0
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what happened!
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
    validations:
      required: true

  - type: dropdown
    id: device
    attributes:
      label: Device Type
      description: What type of device are you using?
      options:
        - Android Phone
        - Android Tablet
        - Emulator
        - Other
    validations:
      required: true

  - type: input
    id: android-version
    attributes:
      label: Android Version
      description: What version of Android are you running?
      placeholder: e.g., Android 12, API 31
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Please copy and paste any relevant log output. This will be automatically formatted into code.
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.

  - type: checkboxes
    id: terms
    attributes:
      label: Quality Checklist
      description: Please confirm the following
      options:
        - label: I have tested this on the latest version
          required: true
        - label: I have searched for existing issues
          required: true
        - label: I have provided sufficient information to reproduce the bug
          required: true
