name: Security and Dependency Check

on:
  schedule:
    # Run weekly on Sundays at 2 AM UTC
    - cron: '0 2 * * 0'
  workflow_dispatch: # Allow manual triggering

permissions:
  contents: read
  issues: write

jobs:
  dependency-check:
    name: Dependency Security Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Make gradlew executable
      run: chmod +x gradlew

    - name: Check for dependency updates
      run: ./gradlew dependencyUpdates

    - name: Upload dependency report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: dependency-updates-report
        path: build/dependencyUpdates/
        retention-days: 30

    - name: Create security issue if vulnerabilities found
      uses: actions/github-script@v7
      if: always()
      with:
        script: |
          const fs = require('fs');
          const path = require('path');
          
          // Check if dependency report exists and has vulnerabilities
          const reportPath = 'build/dependencyUpdates/report.txt';
          
          if (fs.existsSync(reportPath)) {
            const report = fs.readFileSync(reportPath, 'utf8');
            
            if (report.includes('outdated') || report.includes('exceeded')) {
              // Create or update an issue for dependency updates
              const title = '🔒 Dependency Updates Available';
              const body = `## Dependency Update Report
              
          The weekly dependency scan has found updates available for this project.
          
          ### Report Summary
          \`\`\`
          ${report.slice(0, 2000)}
          \`\`\`
          
          Please review and update dependencies as appropriate.
          
          ---
          *This issue was automatically created by the security workflow*`;
              
              // Check if issue already exists
              const { data: issues } = await github.rest.issues.listForRepo({
                owner: context.repo.owner,
                repo: context.repo.repo,
                state: 'open',
                labels: 'dependencies,security'
              });
              
              const existingIssue = issues.find(issue => issue.title.includes('Dependency Updates Available'));
              
              if (existingIssue) {
                await github.rest.issues.update({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: existingIssue.number,
                  body: body
                });
              } else {
                await github.rest.issues.create({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  title: title,
                  body: body,
                  labels: ['dependencies', 'security']
                });
              }
            }
          }
